LBHackney-IT/lbh-frontend-react

package-lock.json, package.json, rollup.config.js, tsconfig.json
We need to use `rollup-plugin-typescript2` instead of `rollup-plugin-typescript`, as the former honours the `declarations` flag in the `tsconfig.json`.
=> Make builds export type declarations

rollup.config.js
We don't want to distribute any type declarations from the tests.
=> Ignore test files when building TypeScript

package.json
Most React projects use module syntax, so using `index.js` by default makes sense. This also means the types are associated to that file automatically, as they share a name.
=> Rename the ES module distributable index.js

.eslintignore, .gitignore, .prettierignore, barrelsby.json, package-lock.json, package.json, rollup.config.js, src/components/ErrorMessage.tsx, src/index.ts
We export ES module syntax for the individual components, as most React build systems will already support that syntax. We still export a CommonJS version with all components bundled in for those users who are unable to use ES modules.
To achieve this, we use `barrelssby` to generate an `index.ts` barrel automatically.
We can't use both named exports and default exports due to name clashes. It's more idiomatic to stick to default exports and to name files after their default export, so we no longer export `ErrorMessage` as a named export.
=> Set up individual component builds

.dependabot/config.yml
We have a lot of dependencies, and requiring manual review of all of them is _very_ time consuming. Packages following SemVer should never introduce breaking changes in minor versions. We might miss out on seeing the introduction of new features. We will continue to get PRs, and have their status checked by CI before merge, so updates won't be completely invisible.
=> Set Dependabot to automerge all minor version changes

package.json, rollup.config.js
We want to be able to offer the benefits of being able to import individual components as needed, to reduce bundle sizes, to all consumers of this package. Making this change supports that, while keeping the dependency small by only including type declarations where they will be used (by ESM imports).
=> Modify builds to build a full hierarchy for both CJS and ESM

.github/pull_request_template.md
This removes the Jira section from the template in favour of a comment recommending using the PR title (as this PR does) for smart commits.
GitHub prefills the merge commit with the PR title, so this reduces the overhead in doing merges, as it doesn't require manual copy operations.
=> MT3-221 #ready-for-test #comment Suggest using the PR title for Jira smart commits

barrelsby.json, src/components/ErrorMessage.test.tsx, src/components/ErrorMessage.tsx
This changes `ErrorComponent` to be a named export rather than a default export, and stops Barrelsby from including default exports in the `index.ts` it generates.
Built CommonJS files with both named and default exports end up looking like:
```
exports.NamedThing = NamedThing;
exports.default = DefaultThing;
```
To access `DefaultThing` in that example, you would need to use `require("package/DefaultThing").default` which is less than ideal.
=> Switch away from using default exports to using only named exports

CHANGELOG.md, docs/adr/0009-build-a-component-register.md, jest.config.js, jest.setup.ts, package-lock.json, rollup.config.js, src/ComponentRegister.test.tsx, src/ComponentRegister.ts, src/components/Link.test.tsx, src/components/Link.tsx, src/components/__snapshots__/Link.test.tsx.snap, tsconfig.json
`Link` is a wrapper for the current routing solution within the consumer application, given that the component used in the library is initialised within `ComponentRegister`. If not initialised, `Link` component will default to an anchor tag.
Adds a component register class that allows the host application to utilise the styles of [lbh-frontend](https://github.com/LBHackney-IT/lbh-frontend) for components that may need to be defined by the host. Also adds a link wrapper component that the host can use when they have registered their respective link component.
The user will need to link between pages within their application. They may also be using one of many different routing methods. The component register allows the host to register any of these methods, so they can use a corresponding …
=> MT3-237 #ready-for-test #comment Add Link component

CHANGELOG.md, src/components/Hint.scss, src/components/Hint.test.tsx, src/components/Hint.tsx, src/components/__snapshots__/Hint.test.tsx.snap
Added Hint component to be used with inputs.
Labels for input fields may require a hint so that the user understands what they need to do easier. 
`lbh-frontend` library: [Github](https://github.com/LBHackney-IT/LBH-frontend/tree/master/src/lbh/components/lbh-header) | [Style guide](https://lbh-frontend.herokuapp.com/components/lbh-input) (see input with hint text)
`govuk-frontend` library : [Github](https://github.com/alphagov/govuk-frontend/tree/master/src/govuk/components/hint) | [Style guide](https://design-system.service.gov.uk/components/text-input/#hint-text)
=> MT3-248 #ready-for-test #comment Add Hint component

CHANGELOG.md, src/components/Label.scss, src/components/Label.test.tsx, src/components/Label.tsx, src/components/__snapshots__/Label.test.tsx.snap
Added label component to be used with inputs.
In order to be accessible, inputs will need to have a label. 
`lbh-frontend` library: [Github](https://github.com/LBHackney-IT/LBH-frontend/blob/master/src/lbh/core/_label.scss) | [Style guide](https://lbh-frontend.herokuapp.com/components/lbh-input) (see inputs with labels)
`govuk-frontend` library : [Github](https://github.com/alphagov/govuk-frontend/tree/master/src/govuk/components/label) | [Style guide](https://design-system.service.gov.uk/components/text-input/) (see inputs with labels)
=> MT3-247 #ready-for-test #comment Add Label component

package-lock.json, package.json
Disable Jekyll for the entire `docs/` directory.
We serve GitHub pages from the root of `docs/`, and Jekyll ignores all files with a leading underscore, by default.
=> Disable Jekyll for the entire `docs/` directory

docs/adr/0011-build-lbh-frontend-and-govuk-frontend-dependencies-into-the-distributables.md
This documents the earlier decision to bundle `lbh-frontend` and `govuk-frontend` into our distributables.
=> Create an ADR documenting the decision to bundle dependencies

.github/CODEOWNERS
Update to use the MaT GitHub team.
That means we don't need to update these individual repositories everytime the team changes.
=> MT3-270 #comment Update `lbh-frontend-react` code owners to use the MaT GitHub team

README.md
This adds 4 new badges to the readme:
- project maturity: alpha
- licence: MIT
- CircleCI: build status
- repo size
Badges are useful for indicating the status of a repository quickly, at a glance.
=> Add status and info badges to the readme

.dependabot/config.yml
Change Dependabot to batch updates daily, instead of live, as they are published.
While always being up-to-date with cutting edge releases of packages is nice, it can also result in a lot of updates. Most don't require manual reviews, but because they're automerged all the time, it can make keeping up with what's changing quite difficult.
This is a library that will be published preiodically. It's not necessary to be absolutely up-to-date all of the time.
=> Make Dependabot update less frequently

.prettierignore
It doesn't know how to handle shell scripts.
=> Ignore `/bin/` from Prettier

.prettierignore
Makes prettier ignore all index files.
Prettier currently only ignores the prettier file inside the src
directory. Now that we will have index files in most directories,
we don't want it formatting them all.
=> Make prettier ignore all index files

bin/bump-version, package.json
Require the branch to match the version number. We know what version we're releasing, so we can enforce the naming convention.
Move `npm install` into `preversion`. We want to run it before the tests regardless of how `npm version` is called.
=> Make some improvements to `bin/bump-version`

bin/publish
- Install after checking the new tag out, but before publishing.
- Push the tag after publishing succeeds.
We want to make sure we're on the latest version of depenedencies before we build for release, and that the tag on the remote really matches the version we released.
=> Install before publishing

CHANGELOG.md, package-lock.json, package.json
@babel/runtime-corejs2 is needed to build the library correctly. Given that we now have components that require this, we need it to be installed so that consumer applications don't run into errors looking for it.
=> Add @babel/runtime-corejs2

bin/publish
We don't need to do a fresh package installation after publishing.
=> Reword feedback to be clearer and do incremental install after publish
